## 00_config.R
##
## Central configuration for the IRTree analysis pipeline.
## Sourced automatically by all other scripts — do not run directly.
##
## To switch between simulated and real data, change `use_simulated_data`.
## All output directories are created here on first run.

# ============================================================
# WORKING DIRECTORY
# ============================================================
# Sets the wd to the folder containing this script, regardless of
# where R is launched from. Handles three cases: Rscript CLI,
# interactive RStudio, and source() calls from other scripts.
.get_script_dir <- function() {
  args     <- commandArgs(trailingOnly = FALSE)
  file_arg <- grep("--file=", args, value = TRUE)
  if (length(file_arg) > 0)
    return(dirname(normalizePath(sub("--file=", "", file_arg))))
  if (requireNamespace("rstudioapi", quietly = TRUE) && rstudioapi::isAvailable()) {
    ctx <- rstudioapi::getSourceEditorContext()
    if (!is.null(ctx) && nchar(ctx$path) > 0)
      return(dirname(normalizePath(ctx$path)))
  }
  src <- tryCatch(dirname(normalizePath(sys.frames()[[1]]$ofile)), error = function(e) NULL)
  if (!is.null(src)) return(src)
  getwd()
}
setwd(.get_script_dir())
rm(.get_script_dir)

# ============================================================
# DATA MODE
# ============================================================
# TRUE  = use simulated data (01_generate_example_data.R); for local testing
# FALSE = use real Prowise Learn data; update data_path below accordingly
use_simulated_data <- TRUE

# ============================================================
# DATA PATHS
# ============================================================
if (use_simulated_data) {
  data_path   <- "data/sim_logs.Rdata"  # generated by 01_generate_example_data.R
  data_object <- "sim_logs"             # R object name inside the .Rdata file
} else {
  data_path   <- "~/research-collaboration/question-mark/new data/logs_clean.Rdata"
  data_object <- "logs_clean"
}

# ============================================================
# ANALYSIS PARAMETERS
# ============================================================

# Users with fewer than min_skips skip responses are excluded (02_irtree_prep.R)
min_skips <- 10

# 10-fold cross-validation settings (04_irtree_kfolds.R)
n_folds      <- 10   # number of folds
holdout_frac <- 0.1  # fraction of responses held out per fold per node

# Random seed shared across all scripts for reproducibility
random_seed <- 1234

# ============================================================
# DIRECTORY STRUCTURE
# ============================================================
# Defines all output paths and creates them if they don't exist.
# No manual folder setup is needed on a fresh clone.
#
#   code/
#   ├── data/            input data (simulated or real)
#   └── results/
#       ├── models/      fitted model objects     <- 03_irtree_fit.R
#       ├── k_folds/     cross-validation output  <- 04_irtree_kfolds.R
#       └── plots/       exported figures         <- 05_itree_analysis.Rmd

data_dir    <- "data"
results_dir <- "results"
models_dir  <- file.path(results_dir, "models")
kfolds_dir  <- file.path(results_dir, "k_folds")
plots_dir   <- file.path(results_dir, "plots")

for (.d in c(data_dir, results_dir, models_dir, kfolds_dir, plots_dir)) {
  dir.create(.d, showWarnings = FALSE, recursive = TRUE)
}
rm(.d)
